### ISSUE TITLE
Hxcpp hack not working

### ISSUE THREAD

**Issue by Misiur** [eliasku/ecx#10]
Hello! There seems to be a problem with hxcpp unsafe cast hack. 
https://github.com/Misiur/haxe34crasher/tree/03f9f4adef43d8618c3efbe7928f0c8c8eeb335f (name of repo is misleading, it is tied to hxcpp not haxe version).

More info https://github.com/HaxeFoundation/haxe/issues/5994#issuecomment-283697175

**Comment by Misiur** [comment]
Anybody'd be instested if I posted a bounty? I'd really would love to this be fixed for haxe 4 release

**Comment by eliasku** [comment]
@Misiur please check if you are still interested. I didn't check generated c++ code, but compilation passed
