### ISSUE TITLE
Compilation issues with haxe4

### ISSUE THREAD

**Issue by sh-dave** [eliasku/ecx#18]
Hi, trying to build some simple project with haxe 4 currently fails. A sample repo is available [here](https://github.com/sh-dave/ecx-haxe4-issue.git).

### haxe 4 preview 4

```shell
libs/ecx/src/ecx/macro/SystemBuilder.hx:12: characters 23-46 : Uncaught exception Cannot call null
```
### haxe 4 [latest git](https://github.com/HaxeFoundation/haxe/tree/7012dfb84eb705d49c37a1b536bafeb9f154ecf4)

```shell
libs/ecx/src/ecx/macro/SystemBuilder.hx:111: characters 30-35 : Uncaught exception Unbound variable
libs/ecx/src/ecx/macro/SystemBuilder.hx:36: characters 21-41 : Called from here
libs/ecx/src/ecx/macro/SystemBuilder.hx:25: characters 3-41 : Called from here
```

**Comment by eliasku** [comment]
Hi @sh-dave ,
I commit changes to support the latest Haxe4. Try `ecx` develop branch.
You could use `haxe test.node.js.hxml` to compile and run local tests with NodeJS
Let me know if compilation issues are gone.

**Comment by sh-dave** [comment]
Looking good, haven't run the tests as i don't have haxelib installed, but my test project still works fine.
