### ISSUE TITLE
Mb. strict type-check is better there?

### ISSUE THREAD

**Issue by fzzr-** [eliasku/ecx#3]
I mean [this workaround](https://github.com/eliasku/ecx/blob/master/src/ecx/World.hx#L183-L184):

```haxe
public function addComponent<T:Component>(entity:Entity, component:T, type:ComponentType):T {
	// workaround for old hxcpp
	var comp:Component = component;
	components[type.id][entity.id] = comp;
```

I don't know why and for what it but if it needed I think strict type-check will better there:

```haxe
	components[type.id][entity.id] = (component : Component);
```

What do you think? ;)

**Comment by eliasku** [comment]
Workaround should be removed after drop `haxe 3.2.1 ` support. It was done to eliminate cpp dynamic_cast generated. Local variable was used to not duplicate compile-cast for other calls.
It's now very hard to keep code compilable across the platforms (thanks CI!!). But I'm very focused on using the latest Haxe version to compile cpp code.

**Comment by fzzr-** [comment]
Okay. I think issue can be closed :)
