### ISSUE TITLE
Custom component storage

### ISSUE THREAD

**Issue by OvermindDL1** [eliasku/ecx#4]
Currently it seems that components must be allocated on the heap and a pointer is stored, this is bad for cache, which really only matters in tight loops, but I've always implemented my ECS's by having the `Component` parent class be something like `ComponentStorage` or so, and the subclass defines however they wish to store it, such as a tightly-packed array for components that are common, like Position2Df, or a sparse array for a quadtree component, a hash-map for rare components, pointers, etc..., or whatever other structure is appropriate.

A single ComponentStorage may store multiple useful things, for example I often have Position2Df (actually a full transformation) as well as physics information all in the same storage as it makes for *extremely* fast vectorization paths (can process a million moving positions in 60fps if made properly) and lookups in systems are more like this (in ecx'ish syntax):
```haxe
class MovementSystem extends System {
    var _tp:Wire<TransPhyStorage>;
    var _entities:Family<Transform, Node, Renderable>;
    ...
    override function update() {
        // Note: typeof _entities in my systems is usually something like SortedSet<Entity>
        for(entity in _entities) {
            var trans = _tp.getTransformation(entity);
            var phys = _tp.getPhysics(entity);
            // do stuff
        }
    }
}
```
Or in that above specific case I often do not bother keeping a family at all and just vectorized operate over the entire packed array of transformation and physics data, which is exceedingly fast, and the few entities that do not have such components are so rare and the vectorized throughput so fast that it has never even gotten close to mattering.

This would flip the calls of things like
```haxe
views[i].create(EcxPosition1).randomize();
```
To become like:
```haxe
ecxPosition1.randomize(entity);
```
As you cannot have a unified method of accessing a component as each storage can do things in their own unique ways (unless you have something like a generic 'get' that returns the entire structure as a 'view' object to modify, but it is heavy-weight and I've not used that style in years, component access is necessarily dependent on the component and not generic, no point trying to hide that).  I also find this access far more logical as well as every component can be thought of as an array (regardless of how it is internally) and you are just indexing into the array with the entity as the index value.

Thus have you thought of a style more like this?  Where you still have Family, but you can Wire up storages to components instead of passing pointers all over the place, thus allowing for tightly packed storage in cases where it matters?  You could even keep the current `Component` pointer API built on top of that model with potentially other subclasses of `ComponentStorage` (like `ComponentArray`, `ComponentMap`, `ComponentSparseArray`, etc...) that people could use to build off of to reduce the boilerplate?

References:
* ECX Currently allocates every object on the heap:  https://github.com/eliasku/ecx/blob/master/src/ecx/EntityView.hx#L43
* I have a very low level C++ version of what I described (that I really need to clean up and finish fixing up before I properly release, my internal complete version is very baked into my engine right now, this repo was being used to demonstrate a few styles of things, not as something to use):  https://github.com/OvermindDL1/OverECS/blob/master/main.cpp

**Comment by eliasku** [comment]
Thank you for high-detailed proposal and the time wasted to review `ecx` library :) 

Again, I agreed at all points. I fully understand what are you talking about. 

I have the same thoughts all the time. And my first unreleased version of `ecx` was very DOD-style. For example `TransformComponent` storage was just `Float32[capacity*6]` storage + separated `BitArray` for dirty state, but syntax was strange and over-sized, but from that point I'd experience, and decided to implement these custom performance-critical linear component's storages after the ease API will be ready.

What I especially like from your point of view:
1. Capability to customize component-storage with the most efficient data structure.
2. Request to work with the data only from the `System` scope.

I will review and think on your design decisions (from cpp code-base).

I think I will release `v0.1.0` and will start to design new more efficient component-data-table storage for `v0.2.0`. Now a lot of things need to be done.

**Comment by OvermindDL1** [comment]
Thanks for looking at this.  I never found a decent C++ ECS library so I made my own (this was *years* ago, unsure if the situation has changed), and recently been getting into Haxe and although I've been making mini-ecs's I am not pleased about making another one with the speed and feature-set that my C++ one has so I found the best designed ECS library that I could find (this one) and am now poking it to see if I can steer development any.  ^.^

But yes, my ECS does follow you 'ECX' style view (as I have many system-like things that both do not operate over any entities and others that do not even have any instanced class at all).  Mine also allows the user to be able to parallize computation with ease (as long as they know what they are doing, which I hope I did as I was the only user of mine), but nothing internal restricted that as all 'changes' were either done to pre-existing components or larger changes were batched up (oh you have no idea how much C++ lambdas simplified this part when they came out) to run post-parallel.

But overall mine was exceedingly fast, had a couple of interesting design points because of the focus on speed but those could be fixed and simplified while retaining their speed in haxe.

As stated though, my cpp code is just showing a couple of the design points from my inner larger ECS, the ones it was showing off was how components were designed (the parent ComponentTable with a macro to handle registration and such), the Aspect system (like your families, my example just used a simple unsorted table where my internal one is actually a sorted set with a custom set storage, hence why it was not easy to pull out to this example, my Aspects can be used anywhere though, not just in systems, but it does assume they are set up 'early' as adding an Aspect can be slow (though any duplicate Aspect's used the same memory and access so making another Aspect that is identical to another existing one was 'free')), as well as  how the event system worked (although it could handle arbitrary indirect/virtual function calls, those were sparsely used, and never really in the engine itself, most callbacks, such as a component being setup for an entity or and entity being removed were usually direct calls of editing the base generation structure in various areas, which translated to being *extremely* fast (though internally the generation structure is stored 'elsewhere' then how it is in my demo).  Basically 'something' could register an array, or hashmap, or whatever to receive direct mutation calls from the event system without needing to go through a slow indirect/virtual function call (though many systems still used those on occasion, like the transformation system could get a callback on entity creation using it so it could `identity`-out its transformation matrix, although in my system I had an event handler that handled those too, it was fairly easy to build extras on-top of the function calls as they just went through the main system call path, could probably make it fairly generic too).

Love the current development path though, looking forward to how it continues to develop.  If I get time I will try to PR anything that might be useful as well.  :-)

**Comment by eliasku** [comment]
@OvermindDL1 Apologise, I can't intelligently read your reply right now because of work. But could you check new version on `master`. Look benchmark repo for usage: https://github.com/eliasku/ecx-benchmarks

Benchmark looks good:
OLD: https://eliasku.github.io/ecx_benchmarks.html
NEW: https://eliasku.github.io/ecx2_versus.html

Things I've made:
- new component API (not limited to class instances now)
- delete all generalization for Component usage
- remade Service / systems / component desing
- AutoComp builder just allow you to generate old class-based components
- FamilyData has efficient EntityMultiSet (which is sorted for cache efficiency)

Waiting for your opinion on these changes. Anyway I love new performance. Despite the fact that a lot generalizations and handy shortcuts have been removed at all.

**Comment by OvermindDL1** [comment]
Nice benchmark improvement!

Initial thoughts:
* Love the new component definition, being able to choose a raw class or define your own table storage is a **huge** help in many workloads, *especially* movement and position as the cache benefits there can be multiple factors of improvement there (where elsewhere it is not always that useful, but still faster).
* I notice that `Entity` is `new`'d.  I'm still in the process of learning the details of Haxe over CPP but if this ends up on the stack instead of actually allocating memory then that is fine.  If however it actually allocates memory, specifically of size `sizeof(int)` as it looks, then this incurs an extra indirection everywhere entities are accessed, makes serialization more difficult as not storing Entities inline (say via a 'Parent' component) and still leaves a problem of dangling ID's and invalidating old entities that may be around that were copied to, say, the stack or so.  The traditional method of handling this is for an Entity ID to actually be a 64-bit integer (or more technically, 2 32-bit integers), where the lower 32 bits are the lookup ID of the entity (the part the current `Entity` is using) and the higher 32-bits is a 'generation id'.  Basically your `_pool` in World should actually be a (usually dynamically growing) array (no need for a ring) of 32-bit integers.  The index of each cell is the entity ID and the value of each cell is its current generation.  To verify if a given Entity (which technically does not even need to be a class, just a 64-bit integer is fine) you just ask the world if it is valid, the world then uses the lower 32-bits to lookup into the array and compare the higher 32-bits to the array value, if equal then the Entity handle is valid, if non-equal then it is non-valid.  To destroy an entity you just increment its value on the array (thus invalidating all entities) and store its ID onto the end of a dynamically growing array, the dead array (this could be a ring if you want), other styles just use a 'dead' flag on the generation value so if odd it is alive and if even it is dead then iterate through it, which is perfectly acceptable but does cause a slight overhead in iteration where a dead array you can just pack it on to the end.  The reason is you want to re-use entities as much as possible as they are created and destroyed (to keep the component tables as small as possible) and you want to invalidate them (hence a generation ID).  What this means is that Entity then becomes a 64-bit integer, no more, no less.  You can wrap a class around it if you want for helpers to call in to World and such, but that is honestly superfluous and does not really shorten code any or make it more readable in my experience, but if you do keep the Entity class on the stack and passed by value, passing a pointer is a lot of extra work for no gain.
* AutoComp looks like it uses an array of pointers, it should probably be configurable in some way so you could select the two most common usages for Components, a map of values (great for sparse components, like something about to go boom), and an array of values (very common things, like if a third of things have this component then this is often better than a map unless the component data is particularly large), and if you could specify the value as either the value or a pointer to the value then that would cover cases where components are not just POD (Plain Old Data) and need construction/destruction semantics (which is bad *bad* **BAD** form in ECS, and I've never seen it not able to be worked around it back to POD).  This generic case of an array of pointers kills all possible cache benefits.
* I love the AutoCompBuilder, very convenient!

Side note about the 64-bit entity, a lot of systems just use 32-bits where the lower 24-bits is the entity ID and the upper 8-bits is the generation ID (thus shrinking the generation array too), but I've seen generation conflicts happen in that due to the small size of the generation (0-255) so an entity spontaneously comes back to life that was previously stored.  The 24-bits of entities is usually still more than enough than any game would need.  16-bit/16-bit is also commonly used, but I often need *far* more than 65535 entities in my little games (I often do CA simulations) so I've never been able to use it.  It would be fantastic if the macro system in Haxe could be used to specify the size of the entity ID and the generation ID.  Like you could specify a certain number of bits worth of storage for them that must equal either 8, 16, 32, or 64, then dynamically specify the entity based on that (in CPP this is pretty easy by using an integer of the bitsize in the world template constructor with typedefs for the resultant Entity size and allocate the componenttables by passing in the resolved world type as a template argument for it to pull necessary information from, this is the perfectly configurable method so each game can be unique, I've played with the idea a few times but never changed my big system to use it and just use 32-bits/32-bits).

So overall:
* Entity should be POD, just an integer of some (possible configurable as specified above) size where the lower N-bits is the ID and the higher (M-N)-bits is the generation ID.
* Should be a generation array of entities ID->Generation on World instead of an array of pointers to Entity objects that are alive/dead.
* Autocomp should probably default to something more cache efficient (if it does not already do, I'm not up on Haxe macro generation and memory storage methods yet), a value storage, and probably a configurable storage type between at least 2 if not more default types (array and map (either hashmap or treemap depending), maybe others).

The rest from a cursory view seems pretty awesome.  Definitely will start messing with it soon to make a little game to give it a try.  :-)

And yeah, I always ignore the generalizations and handy shortcuts at first, I make the raw needed things and gradually build-up helpers as I find they are needed instead of pre-emptively making many (that eventually many of which end up not being used).  Proper use of templates in CPP / macros in haxe can simplify huge swaths of code once it is seen how the code is used.  :-)

**Comment by OvermindDL1** [comment]
Also, no 'pure' test on the new benchmark?  :-)

Might want to up the iterations on ECX to maybe a million or so (I usually do initial benchmarks of 1 million with both tightly packed components like Position that near everything has and sparse components that only 1% and another that only 0.001% have), it is running too fast for the times to be accurate.  Maybe add a statistical benchmarker (does haxe have one?) as they take such things into account.  A larger entity count would stress things well though, especially as 1 million entities is not unheard of in my games (though 100k is the common amount I end up having).  ^.^

**Comment by eliasku** [comment]
@OvermindDL1, again I'm not read all the stuff, but from first point: Entity is haxe-abstract, Entity is just Int. So Entity is not an object, even not a class. Haxe-Abstract just allows you to wrap (something like typedef) and add some functions to this underlying type. Underlying type for Entity is `Int` https://haxe.org/manual/types-abstract.html

and additional trick from haxe-abstract: contructor for ` new Entity(some integerr)` - is private to prevent creation from the client-side, client just forced to use families or make @:privateAccess if some hack is required. 

Will read more stuff later, apologise for delays, just tring to give answers sooner

**Comment by eliasku** [comment]
@OvermindDL1 I keep 1000 entities count for benchmark  just to be sure that I test more cache-lines access than just random access. 1000 entities processed by a lot of iterations, and with 15 runs totally to prevent results floating. And I make benchmark for a lot of combinations of cases and targets, so I just need to wait while it will be finished :) 

I have my own "checking" application, I just update transform and invalidate dirty nodes in scene, and I trying to keep 60fps while 200k nodes simulating. I'm running this "internal application" benchmark manually just to be sure performance critical parts of ecx is not broken.

**Comment by eliasku** [comment]
@OvermindDL1 

*Entity Generation+ID* format. We cannot guarantee `64bit integer` value-type for all Haxe targets :(
- Use just 8bit for generation / 24bit for id looks reasonable.
- Why we can't just make linear int32 array to store generation and access if needed with entity index?
- Also I think bits for generation and entity index should be configurable. For instance, small games could use just 16bit integer for entity index. And maybe no generation at all. On other side seems like large game or game-editor should use generation for entity.

For references we could use something like `Passport:Int32Array` component and Ref class which will compare entities with entity index + Passport value


*AutoComp*
AutoComp is just quick replacement for previous version support. I think you already checked out `hot` components in benchmark code (`ecx_hot` package).
But for sure I plan to provide additional builders:
- `ValueComp<T>` just value-type, like `class Name extends ValueComp<String>`
- `BitComp` just implemented with bitarray for dense case (no data needed, just need to know is it enabled or not)

I think I will start with dense storages, and later will add option for sparse case. Seems like sparse option should be enabled by default. And something like `Pack<BitComp>` or `Pack<ValueComp<String>>` should enable dense storage.

*Pure tests*
- Pure tests is in other page - https://eliasku.github.io/ecx2.html I decided to remove them from comparison graph, I just keep them to make sure I'm not broke something critical

To be continued... More topics later 👍

**Comment by OvermindDL1** [comment]
> @OvermindDL1, again I'm not read all the stuff, but from first point: Entity is haxe-abstract, Entity is just Int. So Entity is not an object, even not a class. Haxe-Abstract just allows you to wrap (something like typedef) and add some functions to this underlying type. Underlying type for Entity is Int https://haxe.org/manual/types-abstract.html

Awesome, I was curious if that is what an abstract type was for.

> and additional trick from haxe-abstract: contructor for new Entity(some integerr) - is private to prevent creation from the client-side, client just forced to use families or make @:privateAccess if some hack is required.

What about not new'ing it, just having it on the stack and passed by value entirely?  It is the same size as a pointer and saves an indirection?

> Will read more stuff later, apologise for delays, just tring to give answers sooner

No need to hurry, I'm at work so cannot be around often.  ^.^

> I have my own "checking" application, I just update transform and invalidate dirty nodes in scene, and I trying to keep 60fps while 200k nodes simulating. I'm running this "internal application" benchmark manually just to be sure performance critical parts of ecx is not broken.

Sounds similar to what I test with, cool.  :-)

> * Use just 8bit for generation / 24bit for id looks reasonable.

Probably a good default to just 'work everywhere' yeah.

> * Why we can't just make linear int32 array to store generation and access if needed with entity index?

That is what the generation storage should be yeah.  If the max entities possible is static at construction time then a plain array is best, if however it can grow (as I always program it to be) then an array that resize itself larger as necessary is usual (with a base default size).

> * Also I think bits for generation and entity index should be configurable. For instance, small games could use just 16bit integer for entity index. And maybe no generation at all. On other side seems like large game or game-editor should use generation for entity.

Entirely agree as per my big post (sorry for the size).  Let the person configure via macros to build up the world and how everything access it to specify their own generation and entity ID size.  The number of bits in the ID part will **hard** limit the max number of entities.  As long as both the generation and entity ID bitsizes equal up to 8/16/32/64 then it is easy to package into an int.  :-)

Having no generation is equal to all entities always being alive, which could indeed by fine for a simple game.  A generation of 1-bit is equal to what you have now, each entity is either alive or dead.  A large bit-size allows for more freedom in terms of entities dying and coming to live quickly without accidentally having a zombie entity come alive again if its handle is stored somewhere.

> AutoComp is just quick replacement for previous version support. I think you already checked out hot components in benchmark code (`ecx_hot` package).

Indeed I did, loved that style, more like what I am used to and will no doubt be the style I use regardless.  :-)

Looking forward to more updates!  It's looking fantastic!

**Comment by OvermindDL1** [comment]
It looks like Haxe has (mostly) guaranteed Int type width to 32 bits (due to storage into a Double on certain platforms those can go up to 52-bits).  However there is a specific type that always 'acts' correctly of `haxe.Int32` and `haxe.Int64` with possible costs on platforms to emulate functionality where it is missing.  It might be good to let the user specify the storage type as well in case they want, say, 64-bit on platforms that support it?  I could easily see specifying 32-bit/32-bit with `haxe.Int64` on platforms that support it with a define that falls back to 16/16 or 24/8 or even possibly 20/12 with `haxe.Int32`/`Int` depending on the game.  If it is user configurable than all cases are covered.

https://haxe.org/manual/types-overflow.html

**Comment by eliasku** [comment]
@OvermindDL1 

**Int32/Int64**
I have some points on that:
- Emulation is not allowed for performance reason.
- For dynamic targets (like js) jit perform optimizations when variable is used as regular integer. And Haxe actually guard enough with his type-system well.
- Emulation for `int64` even could be done just with Low/High "Reference"-object instance. Ruin performance just of heap allocated objects access. And emulation code is done just for unification between targets, and prevent common overflow issues, not for performance reason, or providing some new "type"s for Haxe. * On other side Haxe allows you use specific features of target language/runtime * So overall for NO EMULATION for performance reason: allocating on the heap, dispatch, emulation code overhead.

**World capacity**
One of the design decision was to make maximum amount of entities known on World's initialisation. It allows me to reduce "ensure size" checking while accessing arrays across the Haxe targets. And even not all Haxe targets allow you to write efficient `vector` logic just on target-language, because it will be slower than just target's native variable-lenght collections, but target  hides from you how it stores in memory. All targets are different. For example `hxcpp` use virtual array which is actually dense `vector` (elements or pointers are dense stored). And for example `Array` for `js` target - just sparse node-based hash. 
**I just try found the lowest possible way to work with memory, and use the best method.**
So it was clearly where the start is for that problem: 
- efficient fixed value-type arrays (value-type - I mean types which is passed by value and are loaded to stack, structs other words)
- Let's do SoA as much as possible. Because Haxe has no value-type structs (even emulation). And other benefits are obvious: better locality, less GC, etc.
- Use the most efficient fixed-array structures per target. Let's use Haxe to unify all blazing-fast features of concrete targets together.

For **Entity efficient storage**:
- it's already fixed maximum amount.
- Value-type, just unsafe(in crossplatform context) `int` value for entity representation.
- For now situation with ID+Generation not good enough. For generation: 1 bit. For ID: 30-32 bits (depends on target, and I use unsigned ID, on some targets it could be represents as negative value, so I should just unify that across the targets and make sure it not enough painful price)

**Conclusion**: I will ponder on Generations...

**Comment by eliasku** [comment]
@OvermindDL1 If you don't mind, I will close this ticket. We should create new one about Entity References (generation-index or reference-uid or passport object).

Reason to close: new Component Storage API is almost available on dev version, which will be released soon.

**Comment by OvermindDL1** [comment]
All good, I've been finishing setting up scaffolding for a test game when I get time, I've been planning to pull ecx in this weekend and start things up.  I've noticed your other Repo's and they look quite nice.  Currently I'm experimenting with Kha and it looks like it and ECX should work well together.
